# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/xiaomi/taurus/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/xiaomi/taurus/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
    vendor/xiaomi/taurus/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/xiaomi/taurus/proprietary/bin/diag_dci_client:system/bin/diag_dci_client \
    vendor/xiaomi/taurus/proprietary/bin/diag_mdlog:system/bin/diag_mdlog \
    vendor/xiaomi/taurus/proprietary/bin/diag_socket_log:system/bin/diag_socket_log \
    vendor/xiaomi/taurus/proprietary/bin/diag_uart_log:system/bin/diag_uart_log \
    vendor/xiaomi/taurus/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
    vendor/xiaomi/taurus/proprietary/bin/efsks:system/bin/efsks \
    vendor/xiaomi/taurus/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/xiaomi/taurus/proprietary/bin/ks:system/bin/ks \
    vendor/xiaomi/taurus/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/xiaomi/taurus/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/xiaomi/taurus/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/xiaomi/taurus/proprietary/bin/qcks:system/bin/qcks \
    vendor/xiaomi/taurus/proprietary/bin/qmiproxy:system/bin/qmiproxy \
    vendor/xiaomi/taurus/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/xiaomi/taurus/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/xiaomi/taurus/proprietary/bin/ramdump:system/bin/ramdump \
    vendor/xiaomi/taurus/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/xiaomi/taurus/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
    vendor/xiaomi/taurus/proprietary/bin/thermald:system/bin/thermald \
    vendor/xiaomi/taurus/proprietary/bin/usbhub:system/bin/usbhub \
    vendor/xiaomi/taurus/proprietary/bin/usbhub_init:system/bin/usbhub_init \
    vendor/xiaomi/taurus/proprietary/bin/v4l2-qcamera-app:system/bin/v4l2-qcamera-app \
    vendor/xiaomi/taurus/proprietary/bin/fmconfig:system/bin/fmconfig \
    vendor/xiaomi/taurus/proprietary/bin/fm_qsoc_patches:system/bin/fm_qsoc_patches \
    vendor/xiaomi/taurus/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    vendor/xiaomi/taurus/proprietary/bin/gsiff_daemon:system/bin/gsiff_daemon \
    vendor/xiaomi/taurus/proprietary/bin/nl_listener:system/bin/nl_listener

PRODUCT_COPY_FILES += \
    vendor/xiaomi/taurus/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    vendor/xiaomi/taurus/proprietary/etc/firmware/vidc.b00:system/etc/firmware/vidc.b00 \
    vendor/xiaomi/taurus/proprietary/etc/firmware/vidc.b01:system/etc/firmware/vidc.b01 \
    vendor/xiaomi/taurus/proprietary/etc/firmware/vidc.b02:system/etc/firmware/vidc.b02 \
    vendor/xiaomi/taurus/proprietary/etc/firmware/vidc.b03:system/etc/firmware/vidc.b03 \
    vendor/xiaomi/taurus/proprietary/etc/firmware/vidcfw.elf:system/etc/firmware/vidcfw.elf \
    vendor/xiaomi/taurus/proprietary/etc/firmware/vidc.mdt:system/etc/firmware/vidc.mdt \
    vendor/xiaomi/taurus/proprietary/etc/Diag.cfg:system/etc/Diag.cfg

PRODUCT_COPY_FILES += \
    vendor/xiaomi/taurus/proprietary/lib/hw/camera.msm8960.so:system/lib/hw/camera.msm8960.so \
    vendor/xiaomi/taurus/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/xiaomi/taurus/proprietary/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
    vendor/xiaomi/taurus/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
    vendor/xiaomi/taurus/proprietary/lib/libAKM.so:system/lib/libAKM.so \
    vendor/xiaomi/taurus/proprietary/lib/libalsautils.so:system/lib/libalsautils.so \
    vendor/xiaomi/taurus/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/xiaomi/taurus/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
    vendor/xiaomi/taurus/proprietary/lib/libaudioparsers.so:system/lib/libaudioparsers.so \
    vendor/xiaomi/taurus/proprietary/lib/libchromatix_imx132_default_video.so:system/lib/libchromatix_imx132_default_video.so \
    vendor/xiaomi/taurus/proprietary/lib/libchromatix_imx132_preview.so:system/lib/libchromatix_imx132_preview.so \
    vendor/xiaomi/taurus/proprietary/lib/libchromatix_imx132_zsl.so:system/lib/libchromatix_imx132_zsl.so \
    vendor/xiaomi/taurus/proprietary/lib/libchromatix_imx175_default_video.so:system/lib/libchromatix_imx175_default_video.so \
    vendor/xiaomi/taurus/proprietary/lib/libchromatix_imx175_hfr_120fps.so:system/lib/libchromatix_imx175_hfr_120fps.so \
    vendor/xiaomi/taurus/proprietary/lib/libchromatix_imx175_hfr_60fps.so:system/lib/libchromatix_imx175_hfr_60fps.so \
    vendor/xiaomi/taurus/proprietary/lib/libchromatix_imx175_hfr_90fps.so:system/lib/libchromatix_imx175_hfr_90fps.so \
    vendor/xiaomi/taurus/proprietary/lib/libchromatix_imx175_preview.so:system/lib/libchromatix_imx175_preview.so \
    vendor/xiaomi/taurus/proprietary/lib/libchromatix_imx175_zsl.so:system/lib/libchromatix_imx175_zsl.so \
    vendor/xiaomi/taurus/proprietary/lib/libchromatix_imx175l_default_video.so:system/lib/libchromatix_imx175l_default_video.so \
    vendor/xiaomi/taurus/proprietary/lib/libchromatix_imx175l_hfr_120fps.so:system/lib/libchromatix_imx175l_hfr_120fps.so \
    vendor/xiaomi/taurus/proprietary/lib/libchromatix_imx175l_hfr_60fps.so:system/lib/libchromatix_imx175l_hfr_60fps.so \
    vendor/xiaomi/taurus/proprietary/lib/libchromatix_imx175l_hfr_90fps.so:system/lib/libchromatix_imx175l_hfr_90fps.so \
    vendor/xiaomi/taurus/proprietary/lib/libchromatix_imx175l_preview.so:system/lib/libchromatix_imx175l_preview.so \
    vendor/xiaomi/taurus/proprietary/lib/libchromatix_imx175l_zsl.so:system/lib/libchromatix_imx175l_zsl.so \
    vendor/xiaomi/taurus/proprietary/lib/libCommandSvc.so:system/lib/libCommandSvc.so \
    vendor/xiaomi/taurus/proprietary/lib/libconfigdb.so:system/lib/libconfigdb.so \
    vendor/xiaomi/taurus/proprietary/lib/libcsd-client.so:system/lib/libcsd-client.so \
    vendor/xiaomi/taurus/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/xiaomi/taurus/proprietary/lib/lib_dlb_msd.so:system/lib/lib_dlb_msd.so \
    vendor/xiaomi/taurus/proprietary/lib/libdrmdiag.so:system/lib/libdrmdiag.so \
    vendor/xiaomi/taurus/proprietary/lib/libdrmfs.so:system/lib/libdrmfs.so \
    vendor/xiaomi/taurus/proprietary/lib/libdrmtime.so:system/lib/libdrmtime.so \
    vendor/xiaomi/taurus/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/xiaomi/taurus/proprietary/lib/libdsprofile.so:system/lib/libdsprofile.so \
    vendor/xiaomi/taurus/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/xiaomi/taurus/proprietary/lib/libdsucsd.so:system/lib/libdsucsd.so \
    vendor/xiaomi/taurus/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/xiaomi/taurus/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/xiaomi/taurus/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
    vendor/xiaomi/taurus/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/xiaomi/taurus/proprietary/lib/libimage-jpeg-dec-omx-comp.so:system/lib/libimage-jpeg-dec-omx-comp.so \
    vendor/xiaomi/taurus/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/xiaomi/taurus/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
    vendor/xiaomi/taurus/proprietary/lib/libloc_adapter.so:system/lib/libloc_adapter.so \
    vendor/xiaomi/taurus/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/xiaomi/taurus/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
    vendor/xiaomi/taurus/proprietary/lib/libloc_ext.so:system/lib/libloc_ext.so \
    vendor/xiaomi/taurus/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
    vendor/xiaomi/taurus/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    vendor/xiaomi/taurus/proprietary/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
    vendor/xiaomi/taurus/proprietary/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
    vendor/xiaomi/taurus/proprietary/lib/libmmcamera_interface2.so:system/lib/libmmcamera_interface2.so \
    vendor/xiaomi/taurus/proprietary/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
    vendor/xiaomi/taurus/proprietary/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
    vendor/xiaomi/taurus/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/xiaomi/taurus/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/xiaomi/taurus/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/xiaomi/taurus/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/xiaomi/taurus/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
    vendor/xiaomi/taurus/proprietary/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
    vendor/xiaomi/taurus/proprietary/lib/libqcci_legacy.so:system/lib/libqcci_legacy.so \
    vendor/xiaomi/taurus/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
    vendor/xiaomi/taurus/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/xiaomi/taurus/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/xiaomi/taurus/proprietary/lib/libqmi_cci.so:system/lib/libqmi_cci.so \
    vendor/xiaomi/taurus/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
    vendor/xiaomi/taurus/proprietary/lib/libqmi_common_so.so:system/lib/libqmi_common_so.so \
    vendor/xiaomi/taurus/proprietary/lib/libqmi_csi.so:system/lib/libqmi_csi.so \
    vendor/xiaomi/taurus/proprietary/lib/libqmi_csvt_srvc.so:system/lib/libqmi_csvt_srvc.so \
    vendor/xiaomi/taurus/proprietary/lib/libqmi_encdec.so:system/lib/libqmi_encdec.so \
    vendor/xiaomi/taurus/proprietary/lib/libqminvapi.so:system/lib/libqminvapi.so \
    vendor/xiaomi/taurus/proprietary/lib/libqminvapi.so:obj/lib/libqminvapi.so \
    vendor/xiaomi/taurus/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/xiaomi/taurus/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/xiaomi/taurus/proprietary/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
    vendor/xiaomi/taurus/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/xiaomi/taurus/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/xiaomi/taurus/proprietary/lib/libsensor1.so:system/lib/libsensor1.so \
    vendor/xiaomi/taurus/proprietary/lib/libsensor_reg.so:system/lib/libsensor_reg.so \
    vendor/xiaomi/taurus/proprietary/lib/libsensor_test.so:system/lib/libsensor_test.so \
    vendor/xiaomi/taurus/proprietary/lib/libsensor_user_cal.so:system/lib/libsensor_user_cal.so \
    vendor/xiaomi/taurus/proprietary/lib/libxml.so:system/lib/libxml.so \
    vendor/xiaomi/taurus/proprietary/vendor/firmware/libpn544_fw.so:system/vendor/firmware/libpn544_fw.so \
    vendor/xiaomi/taurus/proprietary/lib/hw/nfc.default.so:system/lib/hw/nfc.default.so \
    vendor/xiaomi/taurus/proprietary/lib/hw/power.taurus.so:system/lib/hw/power.taurus.so \
    vendor/xiaomi/taurus/proprietary/lib/libgeofence.so:system/lib/libgeofence.so \
    vendor/xiaomi/taurus/proprietary/lib/libulp2.so:system/lib/libulp2.so \
    vendor/xiaomi/taurus/proprietary/lib/libsurround_proc.so:system/lib/libsurround_proc.so \
    vendor/xiaomi/taurus/proprietary/lib/libI420colorconvert.so:system/lib/libI420colorconvert.so \
    vendor/xiaomi/taurus/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    vendor/xiaomi/taurus/proprietary/lib/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
    vendor/xiaomi/taurus/proprietary/lib/libOmxMux.so:system/lib/libOmxMux.so \
    vendor/xiaomi/taurus/proprietary/lib/libOmxQcelp13Dec.so:system/lib/libOmxQcelp13Dec.so

PRODUCT_COPY_FILES += \
    vendor/xiaomi/taurus/proprietary/lib/libchromatix_s5k3h7a_default_video.so:system/lib/libchromatix_s5k3h7a_default_video.so \
    vendor/xiaomi/taurus/proprietary/lib/libchromatix_s5k3h7a_hfr_120fps.so:system/lib/libchromatix_s5k3h7a_hfr_120fps.so \
    vendor/xiaomi/taurus/proprietary/lib/libchromatix_s5k3h7a_hfr_60fps.so:system/lib/libchromatix_s5k3h7a_hfr_60fps.so \
    vendor/xiaomi/taurus/proprietary/lib/libchromatix_s5k3h7a_hfr_90fps.so:system/lib/libchromatix_s5k3h7a_hfr_90fps.so \
    vendor/xiaomi/taurus/proprietary/lib/libchromatix_s5k3h7a_preview.so:system/lib/libchromatix_s5k3h7a_preview.so \
    vendor/xiaomi/taurus/proprietary/lib/libchromatix_s5k3h7a_zsl.so:system/lib/libchromatix_s5k3h7a_zsl.so
