# Copyright (C) 2011-2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/xiaomi/qcom-common/setup-makefiles.sh

# firmware
PRODUCT_COPY_FILES += \
    vendor/xiaomi/qcom-common/proprietary-4.3/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    vendor/xiaomi/qcom-common/proprietary-4.3/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    vendor/xiaomi/qcom-common/proprietary-4.3/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    vendor/xiaomi/qcom-common/proprietary-4.3/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/xiaomi/qcom-common/proprietary-4.3/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/xiaomi/qcom-common/proprietary-4.3/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    vendor/xiaomi/qcom-common/proprietary-4.3/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw

PRODUCT_COPY_FILES += \
    vendor/xiaomi/qcom-common/proprietary-4.3/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/xiaomi/qcom-common/proprietary-4.3/vendor/lib/libc2d2_a3xx.so:system/vendor/lib/libc2d2_a3xx.so \
    vendor/xiaomi/qcom-common/proprietary-4.3/vendor/lib/libc2d2_z180.so:system/vendor/lib/libc2d2_z180.so \
    vendor/xiaomi/qcom-common/proprietary-4.3/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/xiaomi/qcom-common/proprietary-4.3/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/xiaomi/qcom-common/proprietary-4.3/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/xiaomi/qcom-common/proprietary-4.3/vendor/lib/libllvm-a3xx.so:system/vendor/lib/libllvm-a3xx.so \
    vendor/xiaomi/qcom-common/proprietary-4.3/vendor/lib/libllvm-arm.so:system/vendor/lib/libllvm-arm.so \
    vendor/xiaomi/qcom-common/proprietary-4.3/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/xiaomi/qcom-common/proprietary-4.3/vendor/lib/libOpenVG.so:system/vendor/lib/libOpenVG.so \
    vendor/xiaomi/qcom-common/proprietary-4.3/vendor/lib/libsc-a2xx.so:system/vendor/lib/libsc-a2xx.so \
    vendor/xiaomi/qcom-common/proprietary-4.3/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so

PRODUCT_COPY_FILES += \
    vendor/xiaomi/qcom-common/proprietary-4.3/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/xiaomi/qcom-common/proprietary-4.3/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/xiaomi/qcom-common/proprietary-4.3/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/xiaomi/qcom-common/proprietary-4.3/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/xiaomi/qcom-common/proprietary-4.3/vendor/lib/egl/libGLESv2S3D_adreno.so:system/vendor/lib/egl/libGLESv2S3D_adreno.so \
    vendor/xiaomi/qcom-common/proprietary-4.3/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so
